# -*- coding: utf-8 -*-
"""documentimageclassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkXlnT7x-550oW0g5RKZNl36WxOa5eUT
"""

!sudo apt install tesseract-ocr -y
!pip install pytesseract

import pytesseract
import cv2, os, zipfile
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tqdm import tqdm

zip_path = "/content/test.zip"
extract_folder = "/content/dataset/test/test"


with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extract_folder)

print("Dataset extracted!")

texts = []
labels = []

for cls in os.listdir(extract_folder):
    cls_path = os.path.join(extract_folder, cls)
    if not os.path.isdir(cls_path):
        continue

    print(f"\nProcessing class: {cls}")

    for img_name in tqdm(os.listdir(cls_path)):
        img_path = os.path.join(cls_path, img_name)

        img = cv2.imread(img_path)
        if img is None:
            continue


        text = pytesseract.image_to_string(img)
        texts.append(text)
        labels.append(cls)

vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(texts)

X_train, X_test, y_train, y_test = train_test_split(
    X, labels, test_size=0.2, random_state=42
)

clf = SVC(kernel="linear")
clf.fit(X_train, y_train)

pred = clf.predict(X_test)
print("\nClassification Report:")
print(classification_report(y_test, pred))